"""Annex IV technical documentation generator.

Produces a Markdown technical file following the structure required by
Article 11 / Annex IV of the EU AI Act. Missing information is rendered as
explicit "TO BE COMPLETED" placeholders so the gaps are visible to the
compliance owner and to auditors.
"""

from __future__ import annotations

from datetime import datetime, timezone

PLACEHOLDER = "_TO BE COMPLETED by the provider._"


def _section(value: str | None) -> str:
    return value.strip() if value and value.strip() else PLACEHOLDER


def generate_annex_iv_document(
    *,
    system_name: str,
    version: str,
    provider_name: str | None,
    intended_purpose: str | None,
    description: str | None,
    classification: dict | None,
    hardware_description: str | None = None,
    training_data_description: str | None = None,
    human_oversight_measures: str | None = None,
    accuracy_metrics: str | None = None,
    risk_management_summary: str | None = None,
    lifecycle_changes: str | None = None,
    standards_applied: str | None = None,
    generated_at: datetime | None = None,
) -> str:
    """Render the Annex IV technical documentation as Markdown."""

    ts = (generated_at or datetime.now(timezone.utc)).strftime("%Y-%m-%d %H:%M UTC")
    tier = (classification or {}).get("tier", "unclassified")
    provisions = ", ".join((classification or {}).get("matched_provisions", [])) or "—"
    obligations = (classification or {}).get("obligations", [])

    obligations_md = (
        "\n".join(f"- **{o['article']}** — {o['obligation']}" for o in obligations)
        or "- No obligations recorded. Run a risk assessment first."
    )

    return f"""# Technical Documentation (Annex IV) — {system_name}

> Generated by the compliance platform on {ts}. Document version: {version}.
> Risk classification: **{tier}** (provisions: {provisions})

## 1. General description of the AI system

### 1(a) Intended purpose, provider, version
- **Provider:** {_section(provider_name)}
- **System version:** {version}
- **Intended purpose:** {_section(intended_purpose)}

### 1(b) Interaction with hardware / other systems
{_section(hardware_description)}

### 1(c) Software / firmware versions and update requirements
{_section(lifecycle_changes)}

### 1(d) Forms in which the system is placed on the market
{_section(description)}

## 2. Detailed description of elements and development process

### 2(a) Methods and steps performed for development
{PLACEHOLDER}

### 2(b) Design specifications, architecture and algorithms
{_section(description)}

### 2(d) Training data: provenance, scope, characteristics
{_section(training_data_description)}

### 2(e) Human oversight measures (Article 14)
{_section(human_oversight_measures)}

## 3. Monitoring, functioning and control

### Accuracy, robustness and cybersecurity metrics (Article 15)
{_section(accuracy_metrics)}

## 4. Appropriateness of performance metrics
{PLACEHOLDER}

## 5. Risk management system (Article 9)
{_section(risk_management_summary)}

## 6. Lifecycle changes and versioning
{_section(lifecycle_changes)}

## 7. Harmonised standards applied (full or in part)
{_section(standards_applied)}

## 8. EU declaration of conformity
{PLACEHOLDER}

## 9. Post-market monitoring plan (Article 72)
{PLACEHOLDER}

---

## Applicable obligations from risk classification

{obligations_md}
"""
