"""Article 50 transparency disclosure engine.

Generates the user-facing disclosure payload for a given AI system and
interaction type, plus configuration for the embeddable disclosure widget.
"""

from __future__ import annotations

import enum


class InteractionType(str, enum.Enum):
    CHAT = "chat"
    CONTENT_GENERATION = "content_generation"
    EMOTION_RECOGNITION = "emotion_recognition"
    BIOMETRIC_CATEGORISATION = "biometric_categorisation"
    DEEPFAKE = "deepfake"
    AUTOMATED_DECISION = "automated_decision"


_DISCLOSURE_TEXT: dict[InteractionType, dict[str, str]] = {
    InteractionType.CHAT: {
        "en": "You are interacting with an AI system, not a human.",
        "de": "Sie interagieren mit einem KI-System, nicht mit einem Menschen.",
        "fr": "Vous interagissez avec un système d'IA, et non avec un humain.",
        "nl": "U communiceert met een AI-systeem, niet met een mens.",
        "es": "Está interactuando con un sistema de IA, no con un humano.",
        "it": "Stai interagendo con un sistema di IA, non con un essere umano.",
    },
    InteractionType.CONTENT_GENERATION: {
        "en": "This content was generated by artificial intelligence.",
        "de": "Dieser Inhalt wurde durch künstliche Intelligenz erzeugt.",
        "fr": "Ce contenu a été généré par une intelligence artificielle.",
        "nl": "Deze inhoud is gegenereerd door kunstmatige intelligentie.",
        "es": "Este contenido fue generado por inteligencia artificial.",
        "it": "Questo contenuto è stato generato da un'intelligenza artificiale.",
    },
    InteractionType.EMOTION_RECOGNITION: {
        "en": "An emotion recognition system is in operation. You are being informed as required by the EU AI Act.",
        "de": "Ein Emotionserkennungssystem ist in Betrieb. Sie werden gemäß der EU-KI-Verordnung informiert.",
        "fr": "Un système de reconnaissance des émotions est en fonctionnement, conformément au règlement européen sur l'IA.",
        "nl": "Er is een emotieherkenningssysteem actief. U wordt geïnformeerd zoals vereist door de EU AI-verordening.",
        "es": "Un sistema de reconocimiento de emociones está en funcionamiento, conforme al Reglamento de IA de la UE.",
        "it": "È in funzione un sistema di riconoscimento delle emozioni, come richiesto dal regolamento UE sull'IA.",
    },
    InteractionType.BIOMETRIC_CATEGORISATION: {
        "en": "A biometric categorisation system is in operation. You are being informed as required by the EU AI Act.",
        "de": "Ein biometrisches Kategorisierungssystem ist in Betrieb, gemäß der EU-KI-Verordnung.",
        "fr": "Un système de catégorisation biométrique est en fonctionnement, conformément au règlement européen sur l'IA.",
        "nl": "Er is een biometrisch categoriseringssysteem actief, zoals vereist door de EU AI-verordening.",
        "es": "Un sistema de categorización biométrica está en funcionamiento, conforme al Reglamento de IA de la UE.",
        "it": "È in funzione un sistema di categorizzazione biometrica, come richiesto dal regolamento UE sull'IA.",
    },
    InteractionType.DEEPFAKE: {
        "en": "This image, audio or video content has been artificially generated or manipulated (deep fake).",
        "de": "Dieser Bild-, Audio- oder Videoinhalt wurde künstlich erzeugt oder manipuliert (Deepfake).",
        "fr": "Ce contenu image, audio ou vidéo a été généré ou manipulé artificiellement (deep fake).",
        "nl": "Deze beeld-, audio- of video-inhoud is kunstmatig gegenereerd of gemanipuleerd (deepfake).",
        "es": "Este contenido de imagen, audio o vídeo ha sido generado o manipulado artificialmente (deepfake).",
        "it": "Questo contenuto immagine, audio o video è stato generato o manipolato artificialmente (deep fake).",
    },
    InteractionType.AUTOMATED_DECISION: {
        "en": "This decision was made or supported by an automated system. You have the right to obtain human review.",
        "de": "Diese Entscheidung wurde von einem automatisierten System getroffen oder unterstützt. Sie haben das Recht auf menschliche Überprüfung.",
        "fr": "Cette décision a été prise ou assistée par un système automatisé. Vous avez le droit d'obtenir un examen humain.",
        "nl": "Deze beslissing is genomen of ondersteund door een geautomatiseerd systeem. U heeft recht op menselijke beoordeling.",
        "es": "Esta decisión fue tomada o asistida por un sistema automatizado. Tiene derecho a una revisión humana.",
        "it": "Questa decisione è stata presa o supportata da un sistema automatizzato. Hai diritto a una revisione umana.",
    },
}

_LEGAL_BASIS: dict[InteractionType, str] = {
    InteractionType.CHAT: "Art. 50(1) EU AI Act",
    InteractionType.CONTENT_GENERATION: "Art. 50(2) EU AI Act",
    InteractionType.EMOTION_RECOGNITION: "Art. 50(3) EU AI Act",
    InteractionType.BIOMETRIC_CATEGORISATION: "Art. 50(3) EU AI Act",
    InteractionType.DEEPFAKE: "Art. 50(4) EU AI Act",
    InteractionType.AUTOMATED_DECISION: "Art. 22 GDPR / Art. 86 EU AI Act",
}

SUPPORTED_LANGUAGES = ["en", "de", "fr", "nl", "es", "it"]


def generate_disclosure(
    *,
    system_name: str,
    intended_purpose: str | None,
    interaction_type: InteractionType,
    language: str = "en",
    capabilities_limitations: str | None = None,
    human_oversight: str | None = None,
) -> dict:
    """Build the disclosure payload served to end users / the widget."""

    lang = language if language in SUPPORTED_LANGUAGES else "en"
    return {
        "ai_interaction": True,
        "system_name": system_name,
        "interaction_type": interaction_type.value,
        "legal_basis": _LEGAL_BASIS[interaction_type],
        "language": lang,
        "disclosure_text": _DISCLOSURE_TEXT[interaction_type][lang],
        "system_purpose": intended_purpose,
        "capabilities_limitations": capabilities_limitations,
        "human_oversight": human_oversight,
        "rights_remedies": [
            "Right to an explanation of individual decision-making (Art. 86 EU AI Act)",
            "Right to lodge a complaint with a market surveillance authority (Art. 85 EU AI Act)",
            "Rights under GDPR Art. 15-22 (access, rectification, erasure, objection to automated decisions)",
        ],
    }
